HomeWork/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace HomeWork.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

HomeWork/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using HomeWork.Repositories.Interfaces;
using HomeWork.Model;

namespace HomeWork.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IRepository _repository;
        private readonly IFileOperations _fileOperations;
        public Dictionary<List<string>, List<string>> animals;
        public Dictionary<string, string> animals2 = new Dictionary<string, string>();
        public IndexModel(IRepository repository, IFileOperations fileOperations)
        {
            _repository = repository;
            animals = new Dictionary<List<string>, List<string>>();
            _fileOperations = fileOperations;
        }

        public void OnGet()
        {
            animals.Add(_repository.GetName(), _repository.GetSound());
        }

        public void OnPostSaveFile(Dictionary<string, string> list)
        {
            string result = "";
            animals.Add(_repository.GetName(), _repository.GetSound());
            foreach (var item in animals)
            {
                for (int i = 0; i < item.Key.Count; i++)
                {
                    result += item.Key[i] + " : " +
                    item.Value[i] + Environment.NewLine;

                }
            }

        }
         public void OnPostLoadFile(IFormFile uploadedFile)
         {
             animals2 = _fileOperations.LoadFile(uploadedFile);

         }
    }
}

HomeWork/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeWork.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

HomeWork/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Animal";
}

<form method="post">
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Sound</th>
        </tr>
    </thead>
        @if (Model.animals2.Count < 1)
        {
            @foreach (var item in Model.animals)
            {
                @for (int i = 0; i < item.Key.Count; i++)
                {
                    <tr>
                        <td>@item.Key[i]</td>
                        <td>@item.Value[i]</td>
                    </tr>
                }

            }

        }
        else {
            @foreach(var item in Model.animals2)
            {
                    <tr>
                        <td>@item.Key</td>
                        <td>@item.Value</td>
                    </tr>
                }
            }
        }
    </table>
<input type="submit" value="Save File" asp-page-handler="SaveFile"/>
</form>
<form asp-action="LoadFile" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile"/>
    <br />
    <input type="submit" value="Load" asp-page-handler="LoadFile"/>
</form>

HomeWork/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeWork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HomeWork.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HomeWork</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HomeWork - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>